server:
  port: ${SERVER_PORT}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/v1/auth/**
          filters:
              - StripPrefix=0

        - id: todo-service
          uri: ${TODO_SERVICE_URL}
          predicates:
            - Path=/api/v1/todos/**
          filters:
            - StripPrefix=0

        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=0
#    globalcors:
#      add-to-simple-url-handler-mapping: true
#      corsConfigurations:
#        '[/**]':
#          allowedOrigins:
#            - http://localhost:3000
#          allowedMethods:
#            - GET
#            - POST
#            - PUT
#            - DELETE
#            - OPTIONS
#          allowedHeaders:
#            - "*"
#          allowCredentials: true


    loadbalancer:
      retry:
        enabled:  false

jwt:
  secret: ${JWT_SECRET}
  header: Authorization
  prefix: Bearer

app:
  cors:
    allowed-origins:
      - ${FRONTEND_URL}
      - ${FRONTEND_URL_SERVER}

#management:
#  tracing:
#    sampling:
#      probability: 1.0
#
#  endpoints:
#    web:
#      exposure:
#        include: health,info,prometheus

#otel:
#  service:
#    name: gateway-service
#  exporter:
#    otlp:
#      endpoint: http://otel-collector:4318

