server:
  port: ${SERVER_PORT}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/v1/auth/**
          filters:
              - StripPrefix=0

        - id: todo-service
          uri: ${TODO_SERVICE_URL}
          predicates:
            - Path=/api/v1/todos/**
          filters:
            - StripPrefix=0
#    globalcors:
#      corsConfigurations:
#        '[/**]':
#          allowedOrigins:
#            - http://localhost:5173
#          allowedMethods:
#            - GET
#            - POST
#            - PUT
#            - DELETE
#            - OPTIONS
#          allowedHeaders:
#            - "*"
#          allowCredentials: true

    loadbalancer:
      retry:
        enabled:  false

jwt:
  secret: ${JWT_SECRET}
  header: Authorization
  prefix: Bearer

